# Generated by Django 4.0.6 on 2022-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegisterModel',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(help_text='seller_name', max_length=50)),
                ('seller_email', models.EmailField(help_text='seller_email', max_length=254)),
                ('seller_mobile', models.CharField(help_text='seller_mobile', max_length=15)),
                ('seller_state', models.CharField(help_text='seller_state', max_length=50)),
                ('seller_city', models.CharField(help_text='seller_city', max_length=50)),
                ('seller_password', models.CharField(help_text='seller_password', max_length=50)),
                ('seller_picture', models.ImageField(upload_to='images/sellers/')),
                ('seller_reg', models.DateField(auto_now=True, help_text='seller_registered_date')),
            ],
            options={
                'db_table': 'seller_details',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='product_name', max_length=100)),
                ('product_size', models.CharField(blank=True, help_text='product_size', max_length=10)),
                ('product_price', models.IntegerField(help_text='product_price')),
                ('product_picture1', models.ImageField(upload_to='images/products/')),
                ('product_picture2', models.ImageField(upload_to='images/products/')),
                ('product_picture3', models.ImageField(upload_to='images/products/')),
                ('product_desc', models.CharField(help_text='product_description', max_length=500)),
                ('product_watchlist', models.ManyToManyField(blank=True, help_text='watchlist', related_name='my_watchlist', to='customerapp.customerregistermodel')),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
    ]
