# Generated by Django 4.0.6 on 2022-07-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_sellerregistermodel_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistermodel',
            name='seller_dob',
            field=models.DateField(help_text='seller_dob', null=True),
        ),
    ]
