# Generated by Django 4.0.6 on 2022-07-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_sellerregistermodel_seller_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='product_category',
            field=models.CharField(help_text='product_category', max_length=50, null=True),
        ),
    ]
