# Generated by Django 4.0.6 on 2022-07-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_productsmodel_product_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='product_color',
            field=models.CharField(help_text='product_color', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='product_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='sellerapp.sellerregistermodel'),
        ),
    ]
