# Generated by Django 4.0.6 on 2022-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegisterModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='customer_name', max_length=50)),
                ('customer_email', models.EmailField(help_text='customer_email', max_length=254)),
                ('customer_mobile', models.CharField(help_text='customer_mobile', max_length=15)),
                ('customer_state', models.CharField(help_text='customer_state', max_length=50)),
                ('customer_city', models.CharField(help_text='customer_city', max_length=50)),
                ('customer_password', models.CharField(help_text='customer_password', max_length=50)),
                ('customer_picture', models.ImageField(upload_to='images/customers/')),
                ('customer_reg', models.DateField(auto_now=True, help_text='customer_registered_date')),
            ],
            options={
                'db_table': 'customer_details',
            },
        ),
    ]
