# Generated by Django 4.0.6 on 2022-07-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_statesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatesModel',
        ),
    ]
