# Generated by Django 4.0.6 on 2022-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_delete_statesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregistermodel',
            name='customer_dob',
            field=models.DateField(help_text='customer_dob', null=True),
        ),
    ]
