# Generated by Django 4.0.6 on 2022-07-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_customerregistermodel_customer_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_product_qty', models.IntegerField(help_text='product_quantity')),
                ('cart_product_price', models.IntegerField(help_text='Prodcuts_price')),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_creator', to='customerapp.customerregistermodel')),
            ],
            options={
                'db_table': 'cart_details',
            },
        ),
    ]
