# Generated by Django 4.0.6 on 2022-07-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_productsmodel_product_color_and_more'),
        ('customerapp', '0005_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='cart_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='sellerapp.productsmodel'),
        ),
        migrations.CreateModel(
            name='OrdersModels',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_product_price', models.IntegerField(help_text='order_price')),
                ('order_product_qty', models.IntegerField(help_text='order_product_qty')),
                ('order_date', models.DateTimeField(auto_now=True, help_text='order_date')),
                ('order_status', models.CharField(default='Pending', help_text='order_status', max_length=50)),
                ('order_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='customerapp.customerregistermodel')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productsmodel')),
                ('order_product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_ordered_products', to='sellerapp.sellerregistermodel')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
