# Generated by Django 4.0.6 on 2022-08-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_productsmodel_product_color_and_more'),
        ('customerapp', '0006_cartmodel_cart_product_ordersmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersmodels',
            old_name='order_owner',
            new_name='order_customer',
        ),
        migrations.RemoveField(
            model_name='ordersmodels',
            name='order_product',
        ),
        migrations.RemoveField(
            model_name='ordersmodels',
            name='order_product_price',
        ),
        migrations.RemoveField(
            model_name='ordersmodels',
            name='order_product_qty',
        ),
        migrations.RemoveField(
            model_name='ordersmodels',
            name='order_product_seller',
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='order_amount',
            field=models.IntegerField(default=0, help_text='order_total_amount'),
        ),
        migrations.CreateModel(
            name='OrderProductsModels',
            fields=[
                ('order_products_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_model_id', models.IntegerField(help_text='order_model_id')),
                ('order_product_price', models.IntegerField(help_text='product_price')),
                ('order_product_qty', models.IntegerField(help_text='order_product_qty')),
                ('order_product_total', models.IntegerField(help_text='product_total_price')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='sellerapp.productsmodel')),
                ('order_product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='sellerapp.sellerregistermodel')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
    ]
