# Generated by Django 4.0.6 on 2022-08-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_productsmodel_product_color_and_more'),
        ('customerapp', '0008_ordersmodels_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodels',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productsmodel'),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='order_product_amount',
            field=models.IntegerField(help_text='order_product_amount', null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='order_product_price',
            field=models.IntegerField(help_text='order_price', null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='order_product_qty',
            field=models.IntegerField(help_text='order_product_qty', null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='order_product_seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_ordered_products', to='sellerapp.sellerregistermodel'),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='order_unique_id',
            field=models.CharField(help_text='order_id_from_razorpay', max_length=100, null=True),
        ),
    ]
