# Generated by Django 4.0.6 on 2022-08-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_ordersmodels_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodels',
            name='order_amount',
        ),
    ]
