# Generated by Django 4.0.6 on 2022-08-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0010_remove_ordersmodels_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodels',
            name='order_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='customer_address', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_address_list', to='customerapp.customerregistermodel')),
            ],
            options={
                'db_table': 'customer_address',
            },
        ),
    ]
