# Generated by Django 4.0.6 on 2022-08-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0011_ordersmodels_order_address_customeraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='address',
            new_name='state',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='flat_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='landmark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
