# Generated by Django 4.0.6 on 2022-08-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0014_customerregistermodel_customer_cart_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodels',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='customerapp.customeraddress'),
        ),
    ]
