# Generated by Django 4.0.6 on 2022-08-06 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_productsmodel_product_color_and_more'),
        ('customerapp', '0016_ordersmodels_order_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_message', models.CharField(help_text='feedback_message', max_length=200)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_all_feedbacks', to='customerapp.customerregistermodel')),
                ('feedback_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feedbacks', to='sellerapp.productsmodel')),
                ('feedback_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_feedbacks', to='sellerapp.sellerregistermodel')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
