# Generated by Django 4.0.6 on 2022-08-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0017_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_sentiment',
            field=models.CharField(help_text='sentiment_analysis', max_length=20, null=True),
        ),
    ]
