# Generated by Django 4.0.6 on 2022-08-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_productsmodel_product_color_and_more'),
        ('customerapp', '0018_feedbackmodel_feedback_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodels',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderd_products_list', to='sellerapp.productsmodel'),
        ),
    ]
